### ISSUE TITLE
awslogs.service not found

### ISSUE THREAD

**Issue by srs4bhavin** [MikeSchuette/chef-cwlogs#6]
* service[awslogs] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[awslogs]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '5'
    ---- Begin output of /bin/systemctl --system restart awslogs ----
    STDOUT:
    STDERR: Failed to restart awslogs.service: Unit awslogs.service not found.
    ---- End output of /bin/systemctl --system restart awslogs ----
    Ran /bin/systemctl --system restart awslogs returned 5

    Resource Declaration:

**Comment by srs4bhavin** [comment]
i was missing the 

default['cwlogs']['region'] = 'us-east-1'

would be nice if it was mentioned in the README.

**Comment by prabaaps** [comment]
Please try the following commands based on your Linux version

sudo service awslogs start

If you are running Amazon Linux 2, try the below command
sudo systemctl start awslogsd

i can able to start/stop/restart the awslogs using the above commands

**Comment by Salmankhan456** [comment]
how to install awslogs on ubuntu server
